Repository vantage-ola/track-now, pull requests merged in 2023-12, with the labels that each got.

#6 Created and installed Virtual environment
  .gitignore
  DEPENDENCIES.txt
  README.md
Labels: good first issue

#10 refactor fix/backend
  DEPENDENCIES.txt
  README.md
  backend/app.py
  backend/models.py
Labels: enhancement

#12 fix-data.json-sample.json
  backend/data.json/sample.json
Labels: bug, enhancement

#13 fix/issue #8 and revert back to previous Laptime model
  backend/app.py
  backend/models.py
Labels: bug

#16 feature/error_handling
  backend/app.py
  backend/error_handle.py
Labels: enhancement
